# Generated by Django 5.2.6 on 2025-09-18 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('planning', 'Planning'), ('daily', 'Daily'), ('review', 'Review'), ('retrospectiva', 'Retrospectiva')], max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('acuerdos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('linea_negocio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quien', models.CharField(max_length=200)),
                ('que', models.TextField()),
                ('para_que', models.TextField(blank=True)),
                ('prioridad', models.CharField(default='Pendiente', max_length=50)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.historiausuario')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
